### ISSUE TITLE
No longer builds on Windows due to winapi 0.2 transient dependency

### ISSUE THREAD

**Issue by HybridEidolon** [tmoers/hexplay#8]
Recent versions of rustc fail to build hexplay as winapi 0.2 is incompatible with later versions. Given this crate only uses 2 dependencies, it is probably a straightforward upgrade to fix.

**Comment by tmoers** [comment]
I have updated the termcolor dependency and published a new version. Did that solve your problem?

**Comment by HybridEidolon** [comment]
Yup! Closing since the issue is resolved.
